/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e2e7ff",
        "surface-tint": "#565e73",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#173bab",
        "on-tertiary-fixed": "#00174b",
        "inverse-primary": "#bfc6df",
        "on-surface": "#131b2e",
        "on-secondary-container": "#00217a",
        "error-container": "#ffdad6",
        tertiary: "#000000",
        "tertiary-fixed": "#dbe1ff",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#7c839a",
        "surface-variant": "#dae2fd",
        "secondary-fixed": "#dde1ff",
        background: "#faf8ff",
        "on-error": "#ffffff",
        surface: "#faf8ff",
        "on-primary-fixed": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-fixed-variant": "#003ea8",
        primary: "#000000",
        error: "#ba1a1a",
        "primary-container": "#131b2e",
        "inverse-surface": "#283044",
        "outline-variant": "#c6c6cd",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#708cfd",
        "on-primary-fixed-variant": "#3f465b",
        "on-surface-variant": "#45464c",
        "tertiary-container": "#00174b",
        "primary-fixed-dim": "#bfc6df",
        "primary-fixed": "#dbe2fb",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001453",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#497cff",
        "on-tertiary": "#ffffff",
        secondary: "#3755c3",
        "on-background": "#131b2e",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#b8c4ff",
        "surface-container-highest": "#dae2fd",
        outline: "#76777d",
        "tertiary-fixed-dim": "#b4c5ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-sm": "1rem",
        margin: "2rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        "display-hero": ["var(--font-space-grotesk)"],
        "headline-xl-mobile": ["var(--font-space-grotesk)"],
        "headline-xl": ["var(--font-space-grotesk)"],
        "label-lg": ["var(--font-space-grotesk)"],
        "body-md": ["var(--font-manrope)"],
        "headline-md": ["var(--font-space-grotesk)"],
        "headline-sm": ["var(--font-space-grotesk)"],
        "label-md": ["var(--font-space-grotesk)"],
        "body-lg": ["var(--font-manrope)"],
        "display-hero-mobile": ["var(--font-space-grotesk)"],
        "legal-fineprint": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-space-grotesk)"],
        "label-sm": ["var(--font-space-grotesk)"],
        "body-sm": ["var(--font-manrope)"],
      },
      fontSize: {
        "display-hero": [
          "56px",
          { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-xl": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "22px",
          { lineHeight: "30px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero-mobile": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "legal-fineprint": ["11px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
